brew "neovim"

# Video
brew "ffmpeg"
brew "yt-dlp"

# Git
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "lazygit"

# CLI Tools
brew "starship"
brew "ripgrep"
brew "zoxide"
brew "stow"
brew "fzf"
brew "fd"

brew "fontforge"

# Languages
## Lua
brew "lua"

## Javascript
### Fast Node Manager
brew "fnm"

### Typescript
tap "oven-sh/bun"
brew "bun"
brew "deno"

cask "itsycal"
cask "kitty"

