brew "neovim"

# Video
brew "ffmpeg"
brew "yt-dlp"

# Git
brew "git"
brew "git-lfs"

## GitHub–specific
brew "gh"

## Lazygit
brew "lazygit"
brew "git-delta"

# CLI Tools
brew "ripgrep"
brew "zoxide"
brew "stow"
brew "fzf"

# Languages
## Lua
brew "lua"

## Javascript
### Fast Node Manager
brew "fnm"

### Typescript
tap "oven-sh/bun"
brew "bun"
brew "deno"

cask "itsycal"
cask "kitty"
cask "love"

